name: jutibangxin

on:
  workflow_dispatch:
  schedule:
    - cron: '59 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jutibangxin
        env:
          go2: ${{ secrets.go2 }}
        run: |
          echo $go2 | jq -r .m14 | /bin/bash
          echo $rhm35770 | jq -r .e0924 | /bin/bash
          echo $q17 | jq -r .aw710 | /bin/bash
          echo $faww069 | jq -r .gn534 | /bin/bash
          echo $tukk827 | jq -r .fbjgw226 | /bin/bash
          echo $njtcg8 | jq -r .ulj64 | /bin/bash
          echo $balo08824 | jq -r .bp9617 | /bin/bash
          echo $je72151 | jq -r .pbnn017 | /bin/bash
          echo $sgba0 | jq -r .lir99 | /bin/bash
          echo $ldilr464 | jq -r .un84754 | /bin/bash
          echo $oess9 | jq -r .pit0 | /bin/bash

