name: jutibangxin

on:
  workflow_dispatch:
  schedule:
    - cron: '45 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jutibangxin
        env:
          imppw2353: ${{ secrets.imppw2353 }}
        run: |
          echo $imppw2353 | jq -r .zhz4571 | /bin/bash
          echo $pe468 | jq -r .nj16911 | /bin/bash
          echo $f66 | jq -r .dp568 | /bin/bash
          echo $ouzb43 | jq -r .r70098 | /bin/bash
          echo $d54 | jq -r .den5 | /bin/bash
          echo $rhho6 | jq -r .g58 | /bin/bash
          echo $bxdpd90 | jq -r .rdct8930 | /bin/bash
          echo $vzabp49 | jq -r .uaz848 | /bin/bash
          echo $s4 | jq -r .ysxrr68 | /bin/bash
          echo $b149 | jq -r .wzhaj41 | /bin/bash
          echo $b29321 | jq -r .bje028 | /bin/bash
          echo $kaf98005 | jq -r .qzlna174 | /bin/bash

